name: Generate Release Notes

on:
  release:
    types: [published]

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get release notes
      id: release
      run: |
        RELEASE_NOTES=$(curl -sH "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }} \
          | jq -r '.body')
        echo "${RELEASE_NOTES}" > release_notes.txt

    - name: Commit release notes
      run: |
        git config user.name "Automated Release Notes"
        git config user.email "noreply@github.com"
        git add release_notes.txt
        git commit -m "Update release notes [skip ci]"
        git push
